---
title: "Analysis on severe weather events in the USA"
author: "Luis Escobar Sawa"
date: "27/10/2022"
output:
  pdf_document: default
  html_document: default
subtitle: 'Reproducible Research: Peer-graded Assignment 2'
company: 'John Hopkins University'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analysis on severe weather events in the USA

```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
```


```{r download_dataset, warning=FALSE, cache=TRUE}
dataDir <- "database/"
dataFile <- "NOAA_stormdatabase.csv.bz2"
dataURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"

if(!dir.exists(dataDir)){
    dir.create(dataDir)
}
setwd(dataDir)

if(!file.exists(dataFile)){
    download.file(dataURL, dataFile)
}
data <- read_csv(dataFile)
setwd("..")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
